# Generated by Django 3.0.5 on 2020-07-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(max_length=15)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('direccion_empresa', models.CharField(max_length=150)),
                ('telefono_empresa', models.CharField(max_length=15)),
                ('contacto_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_empresa', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id_estado_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_producto', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estado_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoProveedor',
            fields=[
                ('id_estadoprov', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_prov', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('id_familia', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_familia', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'familia_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('precio_bruto', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('stock_critico', models.IntegerField()),
                ('id_familia', models.IntegerField()),
                ('id_estado_producto', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=100)),
                ('direccion_prov', models.CharField(max_length=100)),
                ('fono_prov', models.CharField(max_length=15)),
                ('email_prov', models.CharField(blank=True, max_length=50, null=True)),
                ('id_rumbo_prov', models.IntegerField()),
                ('id_usuario', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField()),
                ('id_estadoprov', models.IntegerField()),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RumboProveedor',
            fields=[
                ('id_rumbo_prov', models.BigAutoField(primary_key=True, serialize=False)),
                ('rumbo_prov', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rumbo_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewProductosDisponibles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('precio_bruto', models.CharField(max_length=255)),
                ('precio_venta', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('stock_critico', models.IntegerField()),
                ('familia', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'view_productos_disponibles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewProductosNoDisponibles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('precio_bruto', models.CharField(max_length=255)),
                ('precio_venta', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('stock_critico', models.IntegerField()),
                ('familia', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'view_productos_nodisponibles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewProveedores',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_prov', models.CharField(max_length=100)),
                ('rumbo_prov', models.CharField(max_length=100)),
                ('fono_prov', models.CharField(max_length=15)),
                ('direccion_prov', models.CharField(max_length=15)),
                ('email_prov', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_prov', models.CharField(max_length=30)),
                ('cant_pedidos', models.IntegerField()),
            ],
            options={
                'db_table': 'view_proveedores',
                'managed': False,
            },
        ),
    ]
